"""Generic (framework-agnostic) schema for real-log retrieval eval manifests.

Version 1 of the manifest format. Nothing here knows about ADK or
agents-cli: corpora are an open set declared in the manifest (each with a
role and a machine-readable regeneration pin), families are an open
vocabulary, and every task pins the exact bytes (sha256) of the files its
ground-truth spans address. Together with the content-addressed archives
in :mod:`evolve.retrieval.corpus_store`, a manifest is hermetic — it can
be scored on any host without depending on locally installed packages.

Typed with frozen stdlib dataclasses rather than Pydantic: the
``tools/evolve`` subtree is deliberately dependency-free (candidates and
the evaluator run in sandboxed subprocesses with a minimal environment),
and this repo does not depend on Pydantic. Validation is explicit in the
constructors, so malformed manifests fail loudly at load time.

The evaluator's ``kind`` group-by key is a *derived view* of ``family``
(added only at the LocalEvaluator boundary via ``to_evaluator_dict``),
never persisted — one source of truth.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from enum import Enum

SCHEMA_VERSION = 1

# Well-known family names for the two archetypes mined so far. The
# vocabulary is open — non-ADK eval sets may introduce their own.
FAMILY_DEPENDENCY_SYMBOL = "dependency-symbol"
FAMILY_WORKSPACE_FILE = "workspace-file"
FAMILY_TOOL_INTERNALS = "tool-internals"


class SchemaError(ValueError):
    """A manifest violates the schema (bad value, missing ref, version)."""


class CorpusRole(str, Enum):
    """Why agents search this corpus — analytics metadata, never scored on."""

    WORKSPACE = "workspace"
    DEPENDENCY = "dependency"
    DOCS = "docs"
    OTHER = "other"


@dataclass(frozen=True)
class PackagePin:
    """Corpus regenerated by installing a package at an exact version."""

    name: str
    version: str
    subpath: str = ""

    kind = "package"


@dataclass(frozen=True)
class CommandPin:
    """Corpus regenerated by running a command with a pinned tool."""

    command: str
    tool_version: str

    kind = "command"


@dataclass(frozen=True)
class RepoPin:
    """Corpus regenerated by checking out a repository at a commit."""

    url: str
    commit: str
    subpath: str = ""

    kind = "repo"


_PIN_KINDS = {"package": PackagePin, "command": CommandPin, "repo": RepoPin}


def _pin_from_dict(data: dict) -> PackagePin | CommandPin | RepoPin:
    data = dict(data)
    kind = data.pop("kind", None)
    cls = _PIN_KINDS.get(kind)
    if cls is None:
        raise SchemaError(f"unknown corpus pin kind: {kind!r}")
    try:
        return cls(**data)
    except TypeError as exc:
        raise SchemaError(f"bad {kind} pin: {exc}") from exc


@dataclass(frozen=True)
class CorpusDecl:
    """A corpus the manifest's tasks may reference."""

    role: CorpusRole
    pin: PackagePin | CommandPin | RepoPin

    @classmethod
    def from_dict(cls, data: dict) -> CorpusDecl:
        try:
            role = CorpusRole(data["role"])
        except (KeyError, ValueError) as exc:
            raise SchemaError(f"bad corpus role: {data.get('role')!r}") from exc
        return cls(role=role, pin=_pin_from_dict(data["pin"]))

    def to_dict(self) -> dict:
        return {
            "role": self.role.value,
            "pin": {"kind": self.pin.kind, **asdict(self.pin)},
        }


@dataclass(frozen=True)
class Span:
    """A line-addressed ground-truth region of one corpus file."""

    file: str
    start_line: int
    end_line: int

    def __post_init__(self):
        if self.start_line < 1 or self.end_line < self.start_line:
            raise SchemaError(
                f"invalid span for {self.file}: start_line={self.start_line} "
                f"end_line={self.end_line}"
            )


@dataclass(frozen=True)
class Observed:
    """The real, measured cost of the episode this task was mined from."""

    steps: int
    tokens: int
    wall_seconds: float
    agent: str = ""
    case: str = ""


@dataclass(frozen=True)
class RowValidation:
    """Consensus verdict from the multi-validator pass, if one ran."""

    consensus: str
    unanimous: bool
    issues: tuple[str, ...] = ()

    @classmethod
    def from_dict(cls, data: dict) -> RowValidation:
        return cls(
            consensus=data["consensus"],
            unanimous=bool(data["unanimous"]),
            issues=tuple(data.get("issues", ())),
        )

    def to_dict(self) -> dict:
        return {
            "consensus": self.consensus,
            "unanimous": self.unanimous,
            "issues": list(self.issues),
        }


@dataclass(frozen=True)
class EvalTask:
    """One replayable retrieval case pinned to its corpus dependencies."""

    id: str
    family: str
    corpus: str
    query: str
    expected_spans: tuple[Span, ...]
    pins: dict[str, str]  # expected-span file -> sha256 of its exact bytes
    observed: Observed
    validation: RowValidation | None = None
    # Why the agent searched (structural, miner-derived): failure-triggered,
    # pre-write-verification, or orientation. Optional analytics metadata.
    motivation: str | None = None

    @classmethod
    def from_dict(cls, data: dict) -> EvalTask:
        validation = data.get("validation")
        return cls(
            id=data["id"],
            family=data["family"],
            corpus=data["corpus"],
            query=data["query"],
            expected_spans=tuple(Span(**s) for s in data["expected_spans"]),
            pins=dict(data.get("pins", {}).get("files", {})),
            observed=Observed(**data["observed"]),
            validation=RowValidation.from_dict(validation) if validation else None,
            motivation=data.get("motivation"),
        )

    def to_dict(self) -> dict:
        out = {
            "id": self.id,
            "family": self.family,
            "corpus": self.corpus,
            "query": self.query,
            "expected_spans": [asdict(s) for s in self.expected_spans],
            "pins": {"files": dict(self.pins)},
            "observed": asdict(self.observed),
        }
        if self.validation is not None:
            out["validation"] = self.validation.to_dict()
        if self.motivation is not None:
            out["motivation"] = self.motivation
        return out

    def to_evaluator_dict(self) -> dict:
        """The dict LocalEvaluator scores — ``kind`` derived from family."""
        return {
            "kind": self.family,
            "family": self.family,
            "corpus": self.corpus,
            "query": self.query,
            "expected_spans": [asdict(s) for s in self.expected_spans],
            "observed": asdict(self.observed),
        }


@dataclass(frozen=True)
class Provenance:
    """Where the eval set came from."""

    source_run: str = ""
    miner: str = ""
    validation: str = ""


@dataclass(frozen=True)
class RealEvalManifest:
    """The v1 manifest: declared corpora + pinned, validated tasks."""

    provenance: Provenance
    corpora: dict[str, CorpusDecl]
    tasks: tuple[EvalTask, ...]
    corpus_store: str = "corpus"
    schema_version: int = SCHEMA_VERSION

    def __post_init__(self):
        for task in self.tasks:
            if task.corpus not in self.corpora:
                raise SchemaError(
                    f"task {task.id}: corpus {task.corpus!r} is not declared "
                    f"in the manifest's corpora ({sorted(self.corpora)})"
                )

    @classmethod
    def from_dict(cls, data: dict) -> RealEvalManifest:
        version = data.get("schema_version")
        if version != SCHEMA_VERSION:
            raise SchemaError(
                f"unsupported schema_version: {version!r} (expected {SCHEMA_VERSION})"
            )
        return cls(
            provenance=Provenance(**data.get("provenance", {})),
            corpora={
                name: CorpusDecl.from_dict(decl)
                for name, decl in data["corpora"].items()
            },
            tasks=tuple(EvalTask.from_dict(t) for t in data["tasks"]),
            corpus_store=data.get("corpus_store", "corpus"),
        )

    def to_json(self) -> str:
        return json.dumps(
            {
                "schema_version": self.schema_version,
                "provenance": asdict(self.provenance),
                "corpus_store": self.corpus_store,
                "corpora": {n: d.to_dict() for n, d in self.corpora.items()},
                "tasks": [t.to_dict() for t in self.tasks],
            },
            indent=1,
        )
